### ISSUE TITLE
(bug?) Restore prev address

### ISSUE THREAD

**Issue by kvichans** [CudaText-addons/cuda_install_from_github#1]
Плагин при старте показывает непустое значение (адрес FiF), но не предыдущее (адрес CudaSort).
Как так?

**Comment by Alexey-T** [comment]
Плс, пач?

**Comment by kvichans** [comment]
Не обещаю. Может дойдут руки.

**Comment by Alexey-T** [comment]
Pch made :)

**Comment by kvichans** [comment]
можно видимо ввести его собственный адрес и обновить - да?

**Comment by Alexey-T** [comment]
Да

**Comment by kvichans** [comment]
Работает :)
